server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  profiles:
    active: qa
  cloud:
    config:
      server:
        git:
          uri: https://github.com/barrosodegas/configurations-qa-prod
          force-pull: true
          skipSslValidation: true
          deleteUntrackedBranches: true
          basedir: /tmp/config-server # Linux
          cloneOnStart: true
