server:
  port: 8002

spring:
  application:
    name: rest-crud-api-qa # The name of the .properties or .yml file in the Git repository
  profiles:
    active: qa
  cloud:
    config:
      uri: http://localhost:8888 # The config server

management:
  endpoints:
    web:
      exposure:
        include: '*' # Required to run the endoint that updates properties on the client
