server:
  port: 8002

spring:
  application:
    name: rest-crud-api # The name of the ".properties" or ".yml" file in the Git repository
  profiles:
    active: qa
  cloud:
    config:
      uri: http://localhost:8888 # The config server
      profile: qa

management:
  endpoints:
    web:
      exposure:
        include: '*' # Required to run the endpoint that updates properties on the client
